spring:
  application:
    name: producer
  cloud:
    function:
      definition: sendOrder
    stream:
      bindings:
        sendOrder-out-0:
          destination: my-topic-new
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:29092,localhost:39092,localhost:49092

#  cloud:
#    function:
#      definition: uppercase
#      web:
#        path: /uppercase